spring:
  application:
    name: service-a

server:
  port: 8800
eureka:
  instance:
    instance-id: inst001
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/